### ISSUE TITLE
Kuis

### ISSUE THREAD

**Issue by tikaakusumaa** [polinema-gui/tugas-2015-04#1]
Assalamualaikum pak , maaf menganggu.
saya mau bertanya .. hari ini saya ada dispen menjadi mc di acara warung perancis polinema pak.
hari ini saya tidak mengikuti kuis pak, saya ingin bertanya apakah ada kuis susulan pak ? Terimakasih pak ..

**Comment by dhanifudin** [comment]
waalaykumussalam, silahkan koordinasi dengan teman2 yang tidak masuk. saya ada waktu kosong hari jum'at pagi dan hari senin.

**Comment by tikaakusumaa** [comment]
kalau senin ada jam berapa pak ?

**Comment by dhanifudin** [comment]
dari pagi sampe sore

**Comment by tikaakusumaa** [comment]
okey pak terimakasih infonya, kalau jumat selesai jumatan apakah bapak ada waktu kosong ?

**Comment by dhanifudin** [comment]
saya hanya ada waktu kosong pagi hari

**Comment by tikaakusumaa** [comment]
yaah, kita ada jam pak kalau pagi. Okey pak terimakasih infonya , saya diskusikan bersama teman2 dulu pak :)
